# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rangdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, default='<jamming-date>', null=True)),
                ('date_end', models.DateField(blank=True, default='<jamming-date>', null=True)),
                ('time_start', models.IntegerField(default=9)),
                ('time_end', models.IntegerField(default=10)),
            ],
        ),
    ]
